name: Build and Push Versioned Docker Image to ACR

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      version:
        description: 'Image version tag (e.g., v1.0.0)'
        required: true
        default: 'v1.0.0'

jobs:
  build-and-push-acr:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Azure Container Registry
      uses: docker/login-action@v3
      with:
        registry: Acrtest24101982.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and push Docker image with version and latest tags
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./WebApplication1/Dockerfile
        push: true
        tags: |
          Acrtest24101982.azurecr.io/webapplication1:latest
          Acrtest24101982.azurecr.io/webapplication1:${{ github.event.inputs.version }}
